-- ============================================================
-- BRIGHTLEARN DATA ENGINEERING PROJECT 1
-- Snowflake Sales Data Engineering & Analytics
-- ============================================================
--
-- Platform: Snowflake
-- Database: DE_PROJECT2
-- Schema: SALES
--
-- Source datasets:
--   customers.csv
--   products.csv
--   orders.csv
--
-- ============================================================


-- ============================================================
-- 1. DATABASE AND SCHEMA SETUP
-- ============================================================

CREATE DATABASE IF NOT EXISTS DE_PROJECT2;

CREATE SCHEMA IF NOT EXISTS DE_PROJECT2.SALES;

USE DATABASE DE_PROJECT2;

USE SCHEMA SALES;


-- ============================================================
-- 2. TABLE DEFINITIONS
-- ============================================================

CREATE OR REPLACE TABLE CUSTOMERS (
    customer_id VARCHAR(50),
    customer_name VARCHAR(100),
    email VARCHAR(255),
    province VARCHAR(100),
    signup_date DATE
);


CREATE OR REPLACE TABLE PRODUCTS (
    product_id VARCHAR(50),
    product_name VARCHAR(150),
    category VARCHAR(100),
    unit_price NUMBER(10,2)
);


CREATE OR REPLACE TABLE ORDERS (
    order_id VARCHAR(50),
    customer_id VARCHAR(50),
    product_id VARCHAR(50),
    order_date DATE,
    quantity NUMBER
);


-- ============================================================
-- 3. DATA LOADING
-- ============================================================
--
-- The CSV files were loaded using Snowflake Snowsight:
--
-- Database
--   DE_PROJECT2
--      └── SALES
--           ├── CUSTOMERS
--           ├── PRODUCTS
--           └── ORDERS
--
-- Loading method:
--   Load Data → Local File
--
-- The original CSV files were not edited.
--
-- The assignment allows COPY INTO or an equivalent Snowflake
-- loading method.
--
-- If a Snowflake stage is used, the equivalent COPY INTO
-- pattern is shown below. These commands are examples only
-- and should not be executed unless the referenced stage
-- actually exists.
--
-- COPY INTO DE_PROJECT2.SALES.CUSTOMERS
-- FROM @<stage>/customers.csv
-- FILE_FORMAT = (
--     TYPE = CSV
--     SKIP_HEADER = 1
-- );
--
-- COPY INTO DE_PROJECT2.SALES.PRODUCTS
-- FROM @<stage>/products.csv
-- FILE_FORMAT = (
--     TYPE = CSV
--     SKIP_HEADER = 1
-- );
--
-- COPY INTO DE_PROJECT2.SALES.ORDERS
-- FROM @<stage>/orders.csv
-- FILE_FORMAT = (
--     TYPE = CSV
--     SKIP_HEADER = 1
-- );


-- ============================================================
-- 4. DATA VALIDATION
-- ============================================================
--
-- Expected row counts:
--   CUSTOMERS = 50
--   PRODUCTS  = 20
--   ORDERS    = 150
--
-- ============================================================

SELECT
    (SELECT COUNT(*)
     FROM DE_PROJECT2.SALES.CUSTOMERS) AS customers,

    (SELECT COUNT(*)
     FROM DE_PROJECT2.SALES.PRODUCTS) AS products,

    (SELECT COUNT(*)
     FROM DE_PROJECT2.SALES.ORDERS) AS orders;


-- ============================================================
-- 5. QUERY 1
-- EVERY ORDER WITH CUSTOMER AND PRODUCT INFORMATION
-- ============================================================
--
-- Purpose:
-- Combines transactional order data with customer and product
-- information. Line revenue is calculated as quantity multiplied
-- by unit price.
--
-- Business value:
-- Creates a detailed order-level view that can be used for
-- sales analysis and downstream reporting.
--
-- ============================================================

SELECT
    o.order_id,
    o.order_date,
    c.customer_name,
    p.product_name,
    p.category,
    o.quantity,
    p.unit_price,
    o.quantity * p.unit_price AS line_revenue

FROM DE_PROJECT2.SALES.ORDERS AS o

INNER JOIN DE_PROJECT2.SALES.CUSTOMERS AS c
    ON o.customer_id = c.customer_id

INNER JOIN DE_PROJECT2.SALES.PRODUCTS AS p
    ON o.product_id = p.product_id

ORDER BY o.order_id;


-- ============================================================
-- 6. QUERY 2
-- TOTAL REVENUE PER CUSTOMER
-- ============================================================
--
-- Purpose:
-- Calculates the total revenue generated by each customer.
--
-- Business value:
-- Helps identify high-value customers and supports customer
-- retention, segmentation and sales decisions.
--
-- ============================================================

SELECT
    c.customer_id,
    c.customer_name,
    SUM(o.quantity * p.unit_price) AS total_revenue

FROM DE_PROJECT2.SALES.CUSTOMERS AS c

INNER JOIN DE_PROJECT2.SALES.ORDERS AS o
    ON c.customer_id = o.customer_id

INNER JOIN DE_PROJECT2.SALES.PRODUCTS AS p
    ON o.product_id = p.product_id

GROUP BY
    c.customer_id,
    c.customer_name

ORDER BY total_revenue DESC;


-- ============================================================
-- 7. QUERY 3
-- TOTAL REVENUE PER PRODUCT CATEGORY
-- ============================================================
--
-- Purpose:
-- Calculates the total revenue generated by each product
-- category.
--
-- Business value:
-- Shows which product categories contribute the most to sales
-- and can support inventory, marketing and product strategy.
--
-- ============================================================

SELECT
    p.category,
    SUM(o.quantity * p.unit_price) AS total_revenue

FROM DE_PROJECT2.SALES.ORDERS AS o

INNER JOIN DE_PROJECT2.SALES.PRODUCTS AS p
    ON o.product_id = p.product_id

GROUP BY
    p.category

ORDER BY total_revenue DESC;


-- ============================================================
-- 8. QUERY 4
-- TOP 5 CUSTOMERS BY TOTAL SPEND
-- ============================================================
--
-- Purpose:
-- Identifies the five customers with the highest total spend.
--
-- Business value:
-- Helps the business identify its most valuable customers and
-- supports targeted loyalty and customer-retention strategies.
--
-- ============================================================

SELECT
    c.customer_id,
    c.customer_name,
    SUM(o.quantity * p.unit_price) AS total_spend

FROM DE_PROJECT2.SALES.CUSTOMERS AS c

INNER JOIN DE_PROJECT2.SALES.ORDERS AS o
    ON c.customer_id = o.customer_id

INNER JOIN DE_PROJECT2.SALES.PRODUCTS AS p
    ON o.product_id = p.product_id

GROUP BY
    c.customer_id,
    c.customer_name

ORDER BY total_spend DESC

LIMIT 5;


-- ============================================================
-- END OF BRIGHTLEARN DATA ENGINEERING PROJECT 1
-- ============================================================
